GET http://localhost:8081/cart/1

### GET ORDER
GET http://localhost:8081/order


### POST ORDER
POST http://localhost:8081/cart
Content-Type: application/json

{
    "customerId" : 2,
    "productId": 2,
    "qty": 5
}    