POST http://localhost:8080/products
Content-type: application/json

{
    "name": "Reynolds",
    "description": "Gel Pens",
    "stock": 100,
    "price": 10
}

### Get products
GET http://localhost:8080/products/1
Content-Type: application/json
